# Generated by Django 5.0.14 on 2025-10-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dept_course_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dept_course',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
